### ISSUE TITLE
Adding a component to an Entity inside the System's processEntity step doesn't propogate

### ISSUE THREAD

**Issue by kenjinp** [Trixt0r/ecsts#14]
Love this library <3

## Problem
I've tried to add a Component to an Entity during the processEntity method of a System like `entity.components.add(new components.CameraFollow());`, but it seems like that component never gets added. In other Systems, this entity will not have that component attached, even after this process tick. 

## Expected Behavior
I expect that I can add a new component directly to the entity using `entity.components.add(newComponent)` during the processEntity step, and have that component persist in the entity

## Workaround
As a work around, I've had to clone the entity, remove the old entity, add the new component, and add the new entity into the engine. This seems to trigger whatever events are required to keep the entity persistent in the system.

![Screenshot from 2020-06-29 10-08-22](https://user-images.githubusercontent.com/5485824/85989218-81408400-b9f0-11ea-9dfc-6bb3fe0f5350.png)

**Comment by Trixt0r** [comment]
Thank you for the report!
I'll look into it this week.

Can you tell me which version you are using?

**Comment by kenjinp** [comment]
You're welcome, I'm enjoying the library very much! I'm using `v0.3.1` according to my yarn.lock

**Comment by Trixt0r** [comment]
Well, I can not really reproduce the problem, you are describing.
`entity.components` is a `Collection` and adding a new component is a simple push to an array.

It seems like there is an odd configuration in your systems.

Are you sure your other systems have no aspect filters, which might omit entities with the newly added component?

Maybe you could create a minimal example on https://stackblitz.com or https://codesandbox.io to show the problem?
Otherwise I can not help and will close this issue.

Side note: I recommend posting code snippets not as screen shots. Quick copy & paste is easier with those \`\`\``backticks`\`\`\`

**Comment by Trixt0r** [comment]
It might be, that I fixed your issue with v0.4.0. This version contains some bug fixes concerning aspects and adding/removing components at runtime.

**Comment by kenjinp** [comment]
I think that you did fix it because I couldn't replicate the issue. Thanks!
